<a href="https://colab.research.google.com/github/Nandinikhandade/MachineLearning/blob/main/Logistic_Mtcar_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
import os
os.getcwd()
os.chdir("/content/drive/MyDrive")
os.getcwd

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [31]:
df=pd.read_excel('CDAC_DataBook (1).xlsx',sheet_name='mtcars')
df.head()

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 2.9 KB

In [33]:
df = df.drop(["cyl",'disp','drat','qsec','vs','carb'], axis = 1)

In [34]:
df.head()

    mpg   hp     wt  am  gear
0  21.0  110  2.620   1     4
1  21.0  110  2.875   1     4
2  22.8   93  2.320   1     4
3  21.4  110  3.215   0     3
4  18.7  175  3.440   0     3

In [35]:
am_dummies = pd.get_dummies(df.am, drop_first = True,  prefix="am").astype(int)
gear_dummies = pd.get_dummies(df.gear, drop_first = True,  prefix="gear").astype(int)

In [36]:
df = pd.concat([df,am_dummies,gear_dummies],axis = 1)

In [37]:
df.head()

    mpg   hp     wt  am  gear  am_1  gear_4  gear_5
0  21.0  110  2.620   1     4     1       1       0
1  21.0  110  2.875   1     4     1       1       0
2  22.8   93  2.320   1     4     1       1       0
3  21.4  110  3.215   0     3     0       0       0
4  18.7  175  3.440   0     3     0       0       0

In [38]:
df = df.drop(["am","gear"], axis = 1)

In [39]:
df.head()

    mpg   hp     wt  am_1  gear_4  gear_5
0  21.0  110  2.620     1       1       0
1  21.0  110  2.875     1       1       0
2  22.8   93  2.320     1       1       0
3  21.4  110  3.215     0       0       0
4  18.7  175  3.440     0       0       0

In [40]:
df['mpg'].median()

19.2

In [41]:
df['resp_mpg'] = np.where(df['mpg']>df['mpg'].median(),1,0)

In [42]:
df.head()

    mpg   hp     wt  am_1  gear_4  gear_5  resp_mpg
0  21.0  110  2.620     1       1       0         1
1  21.0  110  2.875     1       1       0         1
2  22.8   93  2.320     1       1       0         1
3  21.4  110  3.215     0       0       0         1
4  18.7  175  3.440     0       0       0         0

In [43]:
dt = df.drop(['mpg'],axis=1)

In [44]:

df.head()

    mpg   hp     wt  am_1  gear_4  gear_5  resp_mpg
0  21.0  110  2.620     1       1       0         1
1  21.0  110  2.875     1       1       0         1
2  22.8   93  2.320     1       1       0         1
3  21.4  110  3.215     0       0       0         1
4  18.7  175  3.440     0       0       0         0

In [45]:
x = df.drop(['resp_mpg'], axis = 1)
y = df.resp_mpg

In [46]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=20)

In [47]:

x_train = sm.add_constant(x_train)
x_test = sm.add_constant(x_test)

In [48]:

x_train.head()

    const   mpg   hp     wt  am_1  gear_4  gear_5
13    1.0  15.2  180  3.780     0       0       0
18    1.0  30.4   52  1.615     1       1       0
21    1.0  15.5  150  3.520     0       0       0
12    1.0  17.3  180  3.730     0       0       0
23    1.0  13.3  245  3.840     0       0       0

In [49]:
model = sm.Logit(y_train, x_train).fit()
print(model.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:               resp_mpg   No. Observations:                   25
Model:                          Logit   Df Residuals:                       18
Method:                           MLE   Df Model:                            6
Date:                Tue, 30 Jun 2026   Pseudo R-squ.:                   1.000
Time:                        04:16:36   Log-Likelihood:            -7.7856e-07
converged:                      False   LL-Null:                       -17.148
Covariance Type:            nonrobust   LLR p-value:                 5.896e-06
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const       -233.6103   1.46e+10   -1.6e-08      1.000   -2.85e+10    2.85e+10
mpg           13.3974   5.49e+09   2.44e-09      1.000   -1.08e+10    1.08e+10
hp            -0.9985   1.94e+09  -5.14e-10      1.000   -3.81e+09    3.81e+09
wt            22.9765   3.44e+10   6.68e-10      1.000   -6.74e+10    6.74e+10
am_1          40.7899   6.93e+09   5.88e-09      1.000   -1.36e+10    1.36e+10
gear_4       -11.6201   2.96e+10  -3.93e-10      1.000    -5.8e+10     5.8e+10
gear_5       -46.6120   2.84e+47  -1.64e-46      1.000   -5.56e+47    5.56e+47
==============================================================================

Complete Separation: The results show that there iscomplete separation or perfect prediction.
In this case the Maximum Likelihood Estimator does not exist and the parameters
are not identified.

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [27]:
print(x.columns)

Index(['mpg', 'hp', 'wt', 'am__1', 'gear__4', 'gear__5'], dtype='object')

In [50]:
print(y.value_counts())

resp_mpg
0    17
1    15
Name: count, dtype: int64

In [51]:
print(df.head())

    mpg   hp     wt  am_1  gear_4  gear_5  resp_mpg
0  21.0  110  2.620     1       1       0         1
1  21.0  110  2.875     1       1       0         1
2  22.8   93  2.320     1       1       0         1
3  21.4  110  3.215     0       0       0         1
4  18.7  175  3.440     0       0       0         0